### ISSUE TITLE
The NUS-WIDE dataset

### ISSUE THREAD

**Issue by forrestlly** [jiangqy/ADSH-AAAI2018#4]
Hello! I have an question that I can get the NUS-WIDE.mat from your matlab implement but there is no nus-wide images dataset for pytorch implement. Can the author share the Nus-wide image dataset ?
Thank you very much !

**Comment by jiangqy** [comment]
I have updated the links and password. You can download nus-wide dataset now.

**Comment by forrestlly** [comment]
You're so nice. Thank you very much.

**Comment by josianerodrigues** [comment]
Hi @jiangqy,
Where can I download NUS-WIDE dataset for pytorch?

**Comment by jiangqy** [comment]
@josianerodrigues Hi, please contact the author of NUS-WIDE. Mr. Xindi Shang, (shangxin AT comp.nus.edu.sg) from [nus-wide homepage](http://lms.comp.nus.edu.sg/research/NUS-WIDE.htm)

**Comment by josianerodrigues** [comment]
Thank you!

**Comment by scpmail** [comment]
nus-wide homepage is not opening. how can I download NUS-WIDE dataset.

**Comment by jiangqy** [comment]
I don't know is there any other resources. Maybe you can contact the authors of NUS-WIDE? @scpmail
