### ISSUE TITLE
您好，请问可以提供下DHN的MATLAB代码么？

### ISSUE THREAD

**Issue by zdaiot** [jiangqy/ADSH-AAAI2018#6]
您好，我是一名大学生，最近在看您的这篇论文，感觉特别棒。另外，看到您用MATLAB实现了DHN，请问您能分享下代码么？万分感谢！原作者的代码是caffe的，不太熟悉。

**Comment by jiangqy** [comment]
抱歉我们无法提供DHN代码，请联系论文作者。

**Comment by zdaiot** [comment]
> 抱歉我们无法提供DHN代码，请联系论文作者。

好的，谢谢
