### ISSUE TITLE
How to calculate TOP5K

### ISSUE THREAD

**Issue by liujiangtaoyd** [jiangqy/ADSH-AAAI2018#7]
Dear Author, Hello, I like your work very much, but I have a question to ask you. How is TOP5K calculated in this paper? Does it mean the average retrieval accuracy of the first 5000 images? Thank you very much and look forward to receiving your reply.

**Comment by jiangqy** [comment]
@liujiangtaoyd  Top5k map is the mean average precision based the top5k returned samples.
Please refer to:
[calc_topMap](https://github.com/jiangqy/ADSH-AAAI2018/blob/f03cb71d347e86687b6f6bbd20e0f85a1e0d4ef1/ADSH_pytorch/utils/calc_hr.py#L36)

**Comment by liujiangtaoyd** [comment]
@jiangqy Thank you for your help
